[features]
seeds = false
skip-lint = false

[programs.devnet]
counter_anchor = "DEWptrf6sj7CGL62SWuSCDvkdTZoyHQzXk3zknRgUdWS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://sparkling-intensive-silence.solana-devnet.quiknode.pro/d0132feb23407dcc8f9b73fdc967a35c591776e9/"
wallet  = "~/my-keypair.json"

[scripts]
test = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[dependencies]
anchor-lang = "0.31.1"
anchor-spl  = "0.31.1"

[toolchain]
anchor_version = "0.31.1"