[features]
seeds = false
skip-lint = false

[programs.localnet]
counter_anchor = "BmDHboaj1kBUoinJKKSRqKfMeRKJqQqEbUj1VgzeQe4A"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet  = "~/my-keypair.json"

[scripts]
test = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[dependencies]
anchor-lang = "0.31.1"
anchor-spl  = "0.31.1"

[toolchain]
anchor_version = "0.31.1"